// Generated by JFlex 1.9.2 http://jflex.de/  (tweaked for IntelliJ platform)
// source: src/main/kotlin/dev/meanmail/Nginx.flex

package dev.meanmail;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import java.util.ArrayDeque;
import java.util.Deque;

import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;
import static dev.meanmail.psi.Types.*;


public class NginxLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING_STATE = 2;
  public static final int DQSTRING_STATE = 4;
  public static final int LUA_BLOCK_STATE = 6;
  public static final int LUA_STATE = 8;
  public static final int MAP_STATE = 10;
  public static final int MAP_BLOCK_STATE = 12;
  public static final int GEO_STATE = 14;
  public static final int GEO_BLOCK_STATE = 16;
  public static final int IF_STATE = 18;
  public static final int IF_PAREN_STATE = 20;
  public static final int IF_STRING_STATE = 22;
  public static final int IF_DQSTRING_STATE = 24;
  public static final int DIRECTIVE_STATE = 26;
  public static final int TYPES_STATE = 28;
  public static final int TYPES_BLOCK_STATE = 30;
  public static final int NUM_MAP_STATE = 32;
  public static final int NUM_MAP_BLOCK_STATE = 34;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 
    16, 16, 17, 17
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\1\1\2\22\0\1\1\1\3"+
    "\1\4\1\5\1\6\1\0\1\7\1\10\1\11\1\12"+
    "\1\13\2\0\1\14\1\0\1\15\12\16\1\17\1\20"+
    "\1\0\1\21\1\0\1\22\1\0\32\23\1\0\1\24"+
    "\1\0\1\25\1\26\1\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\40\1\47\1\50\1\51"+
    "\1\52\1\53\1\40\1\54\1\55\1\40\1\56\1\0"+
    "\1\57\1\60\6\0\1\1\32\0\1\1\u01df\0\1\1"+
    "\177\0\13\1\35\0\2\1\5\0\1\1\57\0\1\1"+
    "\240\0\1\1\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\22\0\1\1\1\2\1\3\1\1\10\4\1\5\3\6"+
    "\1\7\1\1\1\10\1\11\2\10\1\1\1\12\1\13"+
    "\2\12\1\14\1\15\1\16\1\17\2\20\1\21\1\22"+
    "\1\23\6\12\1\24\1\25\5\12\1\26\1\27\2\30"+
    "\1\31\2\30\1\32\1\33\1\34\1\30\1\35\1\36"+
    "\1\30\1\37\1\40\2\41\1\1\2\42\1\1\2\43"+
    "\1\44\3\43\1\45\1\46\1\47\1\50\1\43\1\50"+
    "\1\51\1\52\1\12\1\53\3\12\2\54\1\0\2\4"+
    "\1\55\4\4\1\0\1\3\2\56\2\0\1\3\1\12"+
    "\2\56\2\0\4\12\1\0\4\12\1\40\1\30\2\57"+
    "\1\0\1\60\1\0\1\3\1\0\1\3\1\43\1\61"+
    "\1\51\1\43\1\61\1\43\2\62\1\0\1\61\1\0"+
    "\1\63\1\43\1\51\4\12\1\54\1\4\1\64\1\4"+
    "\1\65\2\4\1\56\1\3\1\56\1\0\4\12\1\0"+
    "\5\12\2\57\1\0\1\43\1\3\1\61\2\62\1\0"+
    "\1\43\4\12\4\4\1\3\1\56\11\12\1\0\1\3"+
    "\1\62\1\66\4\12\3\4\1\67\7\12\1\70\5\12"+
    "\3\4\5\12\1\71\1\12\1\72\4\12\2\4\1\73"+
    "\1\74\1\12\1\75\1\12\1\76\1\77\1\100\1\101"+
    "\1\102\1\12\1\4\1\103\1\12\1\104\1\105\1\4"+
    "\1\106\4\4\1\107";

  private static int [] zzUnpackAction() {
    int [] result = new int[282];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\u0157"+
    "\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d\0\u02ae\0\u02df"+
    "\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467"+
    "\0\u0498\0\u04c9\0\u04fa\0\u052b\0\u055c\0\u058d\0\u0372\0\u05be"+
    "\0\u05ef\0\u0620\0\u0372\0\u0651\0\u0682\0\u0372\0\u06b3\0\u0620"+
    "\0\u06e4\0\u0715\0\u0372\0\u0746\0\u0777\0\u0372\0\u0372\0\u07a8"+
    "\0\u0372\0\u07d9\0\u080a\0\u0372\0\u0372\0\u0372\0\u083b\0\u086c"+
    "\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0372\0\u0372\0\u0961\0\u0992"+
    "\0\u09c3\0\u09f4\0\u0a25\0\u0372\0\u0372\0\u0a56\0\u0a87\0\u0372"+
    "\0\u0ab8\0\u0ae9\0\u0372\0\u0372\0\u0372\0\u0b1a\0\u0a56\0\u0b4b"+
    "\0\u0b7c\0\u0372\0\u0bad\0\u0bde\0\u0c0f\0\u0c40\0\u0c71\0\u0ca2"+
    "\0\u0cd3\0\u0d04\0\u0d35\0\u0372\0\u0d66\0\u0d97\0\u0dc8\0\u0372"+
    "\0\u0372\0\u0df9\0\u0e2a\0\u0e5b\0\u0e8c\0\u0ebd\0\u0372\0\u0eee"+
    "\0\u0372\0\u0f1f\0\u0f50\0\u0f81\0\u0fb2\0\u0fe3\0\u1014\0\u1045"+
    "\0\u1076\0\u0467\0\u10a7\0\u10d8\0\u1109\0\u113a\0\u0651\0\u116b"+
    "\0\u119c\0\u11cd\0\u11fe\0\u06e4\0\u122f\0\u1260\0\u1291\0\u12c2"+
    "\0\u12f3\0\u1324\0\u1355\0\u1386\0\u13b7\0\u13e8\0\u1419\0\u144a"+
    "\0\u147b\0\u14ac\0\u14dd\0\u0a56\0\u150e\0\u153f\0\u1570\0\u15a1"+
    "\0\u0a56\0\u0c40\0\u15d2\0\u0cd3\0\u1603\0\u1634\0\u0dc8\0\u0372"+
    "\0\u1665\0\u1696\0\u16c7\0\u16f8\0\u1729\0\u175a\0\u178b\0\u17bc"+
    "\0\u0d04\0\u17ed\0\u0d04\0\u181e\0\u184f\0\u1880\0\u18b1\0\u0372"+
    "\0\u18e2\0\u0467\0\u1913\0\u0467\0\u1944\0\u1975\0\u0372\0\u19a6"+
    "\0\u19d7\0\u1a08\0\u1a39\0\u1a6a\0\u1a9b\0\u1acc\0\u1afd\0\u1b2e"+
    "\0\u1b5f\0\u1b90\0\u1bc1\0\u1bf2\0\u0372\0\u1c23\0\u1c54\0\u1c85"+
    "\0\u1cb6\0\u1ce7\0\u0372\0\u1d18\0\u1d49\0\u1d7a\0\u1dab\0\u1ddc"+
    "\0\u1e0d\0\u1e3e\0\u1e6f\0\u1ea0\0\u1ed1\0\u1f02\0\u1f33\0\u0715"+
    "\0\u1f64\0\u1f95\0\u1fc6\0\u1ff7\0\u2028\0\u2059\0\u208a\0\u20bb"+
    "\0\u20ec\0\u211d\0\u214e\0\u16c7\0\u0372\0\u217f\0\u21b0\0\u21e1"+
    "\0\u2212\0\u2243\0\u2274\0\u22a5\0\u0467\0\u22d6\0\u2307\0\u2338"+
    "\0\u2369\0\u239a\0\u23cb\0\u23fc\0\u0715\0\u242d\0\u245e\0\u248f"+
    "\0\u24c0\0\u24f1\0\u2522\0\u2553\0\u2584\0\u25b5\0\u25e6\0\u2617"+
    "\0\u2648\0\u2679\0\u0715\0\u26aa\0\u0715\0\u26db\0\u270c\0\u273d"+
    "\0\u276e\0\u279f\0\u27d0\0\u0467\0\u083b\0\u2801\0\u083b\0\u2832"+
    "\0\u0715\0\u0715\0\u0715\0\u0715\0\u0715\0\u2863\0\u2894\0\u0467"+
    "\0\u28c5\0\u083b\0\u0715\0\u28f6\0\u083b\0\u2927\0\u2958\0\u2989"+
    "\0\u29ba\0\u0467";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[282];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\23\2\24\2\23\1\25\1\26\14\23\1\27\2\23"+
    "\7\30\1\31\1\30\1\32\2\30\1\33\1\34\1\35"+
    "\4\30\1\36\4\30\1\23\1\37\1\23\5\40\1\41"+
    "\1\42\1\40\1\43\13\40\1\44\34\40\4\45\1\46"+
    "\1\47\1\50\15\45\1\51\34\45\1\52\2\24\1\52"+
    "\1\53\1\54\1\55\1\52\1\56\7\52\1\57\1\23"+
    "\1\52\1\60\2\52\30\60\1\61\1\23\1\52\5\62"+
    "\1\63\50\62\1\64\1\65\1\62\1\52\2\24\1\52"+
    "\1\53\1\54\1\55\1\52\1\56\7\52\1\57\1\23"+
    "\1\52\1\60\2\52\30\60\1\66\1\23\1\52\1\67"+
    "\2\24\1\67\1\53\1\25\1\70\1\67\1\56\7\67"+
    "\1\57\11\67\1\71\3\67\1\72\1\73\13\67\1\74"+
    "\2\67\1\23\1\75\1\67\1\52\2\24\1\52\1\53"+
    "\1\54\1\55\1\52\1\56\7\52\1\57\1\23\1\52"+
    "\1\60\2\52\30\60\1\76\1\23\2\52\2\24\1\52"+
    "\1\53\1\25\1\77\1\52\1\56\7\52\1\57\1\23"+
    "\10\52\1\100\4\52\1\101\6\52\1\102\1\103\6\52"+
    "\1\23\1\75\1\52\1\23\2\24\2\23\1\25\3\23"+
    "\1\104\44\23\1\105\2\23\1\106\2\24\1\107\1\110"+
    "\1\111\1\112\1\106\1\113\1\114\1\115\1\106\1\116"+
    "\3\106\1\23\1\117\1\106\1\120\1\121\1\106\30\120"+
    "\1\122\1\23\1\123\5\124\1\125\1\42\1\124\1\43"+
    "\13\124\1\126\34\124\4\127\1\46\1\130\1\50\15\127"+
    "\1\131\34\127\1\132\2\24\1\133\1\134\1\135\1\136"+
    "\1\137\1\140\7\132\1\141\1\142\1\137\1\143\1\132"+
    "\1\144\1\143\27\145\1\105\1\23\1\146\1\23\2\24"+
    "\2\23\1\25\50\23\1\147\2\23\1\52\2\24\1\52"+
    "\1\53\1\25\1\55\1\52\1\56\7\52\1\57\1\23"+
    "\15\52\1\150\16\52\1\23\1\75\2\52\2\24\1\52"+
    "\1\53\1\54\1\55\1\52\1\56\7\52\1\57\1\23"+
    "\1\52\1\60\2\52\30\60\1\151\1\23\2\52\2\24"+
    "\1\52\1\53\1\25\1\77\1\52\1\56\7\52\1\57"+
    "\1\23\10\52\1\152\4\52\1\153\13\52\1\154\2\52"+
    "\1\23\1\75\1\52\62\0\2\24\56\0\2\25\1\0"+
    "\56\25\16\0\1\155\4\0\1\156\2\0\30\156\1\157"+
    "\20\0\1\27\4\0\1\27\2\0\30\27\21\0\1\27"+
    "\4\0\1\27\2\0\1\160\27\30\21\0\1\27\4\0"+
    "\1\27\2\0\1\160\4\30\1\161\22\30\21\0\1\27"+
    "\4\0\1\27\2\0\1\160\5\30\1\162\21\30\21\0"+
    "\1\27\4\0\1\27\2\0\1\160\16\30\1\163\10\30"+
    "\21\0\1\27\4\0\1\27\2\0\1\160\1\164\26\30"+
    "\21\0\1\27\4\0\1\27\2\0\1\160\23\30\1\165"+
    "\3\30\21\0\1\27\4\0\1\27\2\0\1\160\26\30"+
    "\1\166\3\0\6\40\1\0\1\40\1\0\13\40\1\167"+
    "\34\40\2\41\1\40\3\41\1\25\1\41\1\25\13\41"+
    "\1\170\34\41\16\0\1\171\4\0\1\172\2\0\30\172"+
    "\1\173\2\0\2\40\1\0\56\40\4\45\1\0\1\45"+
    "\1\0\15\45\1\174\34\45\2\47\1\45\1\47\1\25"+
    "\1\47\1\25\15\47\1\175\34\47\2\45\1\0\56\45"+
    "\1\52\2\0\1\52\1\0\1\52\1\77\1\52\1\0"+
    "\7\52\2\0\34\52\2\0\1\52\1\54\1\25\1\0"+
    "\1\54\1\25\1\54\1\176\1\54\1\25\7\54\2\25"+
    "\34\54\2\25\1\54\1\52\2\0\1\52\1\0\1\52"+
    "\1\77\1\52\1\0\5\52\1\177\1\52\2\0\1\52"+
    "\1\200\2\52\30\200\1\201\1\0\2\52\2\0\1\52"+
    "\1\0\1\52\1\77\1\52\1\0\5\52\1\60\1\52"+
    "\2\0\1\52\1\60\2\52\30\60\2\0\1\52\56\62"+
    "\2\0\1\62\2\63\1\62\53\63\2\25\1\63\1\67"+
    "\2\0\1\67\1\0\1\67\1\70\1\67\1\0\7\67"+
    "\1\0\35\67\2\0\2\67\2\0\1\67\1\0\1\67"+
    "\1\70\1\67\1\0\7\67\1\0\35\67\1\202\1\0"+
    "\2\67\2\0\1\67\1\0\1\67\1\70\1\67\1\0"+
    "\7\67\1\0\12\67\1\203\22\67\2\0\2\67\2\0"+
    "\1\67\1\0\1\67\1\70\1\67\1\0\7\67\1\0"+
    "\24\67\1\204\10\67\2\0\2\67\2\0\1\67\1\0"+
    "\1\67\1\70\1\67\1\0\7\67\1\0\23\67\1\205"+
    "\11\67\2\0\2\67\2\0\1\67\1\0\1\67\1\70"+
    "\1\67\1\0\7\67\1\0\24\67\1\206\10\67\2\0"+
    "\1\67\1\52\2\0\1\52\1\0\1\52\1\77\1\52"+
    "\1\0\7\52\2\0\34\52\1\207\1\0\2\52\2\0"+
    "\1\52\1\0\1\52\1\77\1\52\1\0\7\52\2\0"+
    "\11\52\1\210\22\52\2\0\2\52\2\0\1\52\1\0"+
    "\1\52\1\77\1\52\1\0\7\52\2\0\22\52\1\211"+
    "\11\52\2\0\2\52\2\0\1\52\1\0\1\52\1\77"+
    "\1\52\1\0\7\52\2\0\25\52\1\212\6\52\2\0"+
    "\2\52\2\0\1\52\1\0\1\52\1\77\1\52\1\0"+
    "\7\52\2\0\5\52\1\213\26\52\2\0\1\52\1\106"+
    "\2\0\1\106\1\0\3\106\3\0\5\106\1\0\3\106"+
    "\1\121\31\106\2\0\2\106\2\0\1\106\1\0\3\106"+
    "\3\0\1\106\1\116\3\106\1\0\1\214\2\106\1\121"+
    "\31\106\2\0\1\123\1\111\1\25\1\0\1\111\1\25"+
    "\3\111\3\25\5\111\1\25\3\111\1\215\31\111\2\25"+
    "\1\111\1\106\2\0\1\106\1\0\3\106\3\0\3\106"+
    "\1\216\1\106\1\0\2\106\1\217\1\121\1\106\30\217"+
    "\1\220\1\0\2\106\2\0\1\106\1\0\3\106\3\0"+
    "\5\106\1\0\3\106\1\121\5\106\3\221\17\106\1\221"+
    "\1\106\2\0\2\106\2\0\1\106\1\0\3\106\3\0"+
    "\3\106\1\120\1\106\1\0\2\106\1\120\1\121\1\106"+
    "\30\120\2\0\3\106\1\0\21\106\1\121\35\106\2\0"+
    "\1\106\1\0\3\106\3\0\1\214\4\106\1\0\3\106"+
    "\1\121\31\106\2\0\1\106\6\124\1\0\1\124\1\0"+
    "\13\124\1\222\34\124\2\125\1\124\3\125\1\25\1\125"+
    "\1\25\13\125\1\223\34\125\2\124\1\0\56\124\4\127"+
    "\1\0\1\127\1\0\15\127\1\224\34\127\2\130\1\127"+
    "\1\130\1\25\1\130\1\25\15\130\1\225\34\130\2\127"+
    "\1\0\56\127\1\132\2\0\1\132\1\0\1\132\1\226"+
    "\1\132\1\0\7\132\2\0\1\227\33\132\2\0\2\132"+
    "\2\0\1\132\1\0\1\132\1\226\1\132\1\0\7\132"+
    "\1\0\1\230\1\227\33\132\2\0\1\146\1\135\1\25"+
    "\1\0\1\135\1\25\1\135\1\231\1\135\1\25\7\135"+
    "\2\25\1\232\33\135\2\25\1\135\1\233\2\0\1\233"+
    "\1\0\1\233\1\226\1\233\1\0\5\233\1\234\1\233"+
    "\2\0\1\233\1\235\2\233\30\235\1\236\1\0\1\233"+
    "\1\227\2\0\1\227\1\0\1\227\1\226\1\227\1\0"+
    "\7\227\1\0\1\237\34\227\2\0\1\227\16\0\1\240"+
    "\42\0\1\132\2\0\1\132\1\0\1\132\1\226\1\132"+
    "\1\0\5\132\1\143\1\132\2\0\1\227\1\143\2\132"+
    "\30\143\2\0\2\132\2\0\1\132\1\0\1\132\1\226"+
    "\1\132\1\0\7\132\2\0\1\227\33\132\2\0\1\241"+
    "\1\132\2\0\1\132\1\0\1\132\1\226\1\132\1\0"+
    "\5\132\1\143\1\242\2\0\1\227\1\143\2\132\1\143"+
    "\27\145\2\0\2\132\2\0\1\132\1\0\1\132\1\226"+
    "\1\132\1\0\2\132\1\243\4\132\2\0\1\227\33\132"+
    "\2\0\1\132\1\52\2\0\1\52\1\0\1\52\1\77"+
    "\1\52\1\0\7\52\2\0\22\52\1\244\11\52\2\0"+
    "\2\52\2\0\1\52\1\0\1\52\1\77\1\52\1\0"+
    "\7\52\2\0\11\52\1\245\22\52\2\0\2\52\2\0"+
    "\1\52\1\0\1\52\1\77\1\52\1\0\7\52\2\0"+
    "\22\52\1\246\11\52\2\0\2\52\2\0\1\52\1\0"+
    "\1\52\1\77\1\52\1\0\7\52\2\0\23\52\1\247"+
    "\10\52\2\0\1\52\16\0\1\155\60\0\1\156\4\0"+
    "\1\156\2\0\30\156\1\0\1\250\24\0\1\156\2\0"+
    "\30\156\21\0\1\27\4\0\1\27\2\0\1\160\1\30"+
    "\1\251\25\30\21\0\1\27\4\0\1\27\2\0\1\160"+
    "\16\30\1\252\10\30\21\0\1\27\4\0\1\27\2\0"+
    "\1\160\2\30\1\253\24\30\21\0\1\27\4\0\1\27"+
    "\2\0\1\160\17\30\1\254\7\30\21\0\1\27\4\0"+
    "\1\27\2\0\1\160\14\30\1\255\12\30\21\0\1\27"+
    "\4\0\1\27\2\0\1\160\17\30\1\256\7\30\3\0"+
    "\2\41\1\0\56\41\16\0\1\171\60\0\1\172\4\0"+
    "\1\172\2\0\30\172\1\0\1\257\24\0\1\172\2\0"+
    "\30\172\3\0\2\47\1\0\56\47\1\54\1\25\1\0"+
    "\1\54\1\25\1\54\1\176\1\54\1\25\7\54\2\25"+
    "\34\54\1\260\1\25\1\54\1\52\2\0\1\52\1\0"+
    "\1\52\1\77\1\52\1\0\5\52\1\177\1\52\2\0"+
    "\34\52\2\0\2\52\2\0\1\52\1\0\1\52\1\77"+
    "\1\52\1\0\5\52\1\200\1\52\2\0\1\52\1\200"+
    "\2\52\30\200\1\0\1\257\1\52\23\0\1\261\2\0"+
    "\30\261\26\0\1\262\2\0\30\262\3\0\1\67\2\0"+
    "\1\67\1\0\1\67\1\70\1\67\1\0\7\67\1\0"+
    "\13\67\1\263\21\67\2\0\2\67\2\0\1\67\1\0"+
    "\1\67\1\70\1\67\1\0\7\67\1\0\27\67\1\264"+
    "\5\67\2\0\2\67\2\0\1\67\1\0\1\67\1\70"+
    "\1\67\1\0\7\67\1\0\10\67\1\265\24\67\2\0"+
    "\2\67\2\0\1\67\1\0\1\67\1\70\1\67\1\0"+
    "\7\67\1\0\21\67\1\266\13\67\2\0\1\67\23\0"+
    "\1\267\2\0\30\267\3\0\1\52\2\0\1\52\1\0"+
    "\1\52\1\77\1\52\1\0\7\52\2\0\12\52\1\270"+
    "\5\52\1\271\13\52\2\0\2\52\2\0\1\52\1\0"+
    "\1\52\1\77\1\52\1\0\7\52\2\0\7\52\1\272"+
    "\24\52\2\0\2\52\2\0\1\52\1\0\1\52\1\77"+
    "\1\52\1\0\7\52\2\0\23\52\1\273\10\52\2\0"+
    "\2\52\2\0\1\52\1\0\1\52\1\77\1\52\1\0"+
    "\7\52\2\0\22\52\1\274\11\52\2\0\1\52\2\111"+
    "\1\0\21\111\1\215\34\111\1\106\2\0\1\106\1\0"+
    "\3\106\3\0\3\106\1\216\1\106\1\0\3\106\1\121"+
    "\31\106\2\0\2\106\2\0\1\106\1\0\3\106\3\0"+
    "\3\106\1\217\1\106\1\0\2\106\1\217\1\121\1\106"+
    "\30\217\1\0\1\275\1\106\23\0\1\276\2\0\30\276"+
    "\3\0\2\125\1\0\56\125\2\130\1\0\56\130\1\233"+
    "\2\0\1\233\1\0\1\233\1\226\1\233\1\0\7\233"+
    "\2\0\34\233\1\277\1\0\1\233\1\300\1\25\1\0"+
    "\1\300\1\25\1\300\1\231\1\300\1\25\7\300\2\25"+
    "\34\300\1\301\1\25\1\300\1\232\1\25\1\0\1\232"+
    "\1\25\1\232\1\231\1\232\1\25\7\232\1\25\1\302"+
    "\34\232\2\25\1\232\1\233\2\0\1\233\1\0\1\233"+
    "\1\226\1\233\1\0\7\233\2\0\34\233\2\0\2\233"+
    "\2\0\1\233\1\0\1\233\1\226\1\233\1\0\5\233"+
    "\1\234\1\233\2\0\34\233\2\0\2\233\2\0\1\233"+
    "\1\0\1\233\1\226\1\233\1\0\5\233\1\235\1\233"+
    "\2\0\1\233\1\235\2\233\30\235\1\0\1\303\1\233"+
    "\23\0\1\304\2\0\30\304\3\0\1\237\2\0\1\237"+
    "\1\0\1\237\1\0\1\237\1\0\7\237\1\0\35\237"+
    "\2\0\1\237\16\0\1\305\42\0\1\132\2\0\1\132"+
    "\1\0\1\132\1\226\1\132\1\0\4\132\1\306\2\132"+
    "\2\0\1\227\33\132\2\0\1\132\1\52\2\0\1\52"+
    "\1\0\1\52\1\77\1\52\1\0\7\52\2\0\7\52"+
    "\1\307\24\52\2\0\2\52\2\0\1\52\1\0\1\52"+
    "\1\77\1\52\1\0\7\52\2\0\12\52\1\310\21\52"+
    "\2\0\2\52\2\0\1\52\1\0\1\52\1\77\1\52"+
    "\1\0\7\52\2\0\7\52\1\311\24\52\2\0\2\52"+
    "\2\0\1\52\1\0\1\52\1\77\1\52\1\0\7\52"+
    "\2\0\20\52\1\312\13\52\2\0\1\52\16\0\1\27"+
    "\4\0\1\27\2\0\1\160\26\30\1\313\21\0\1\27"+
    "\4\0\1\27\2\0\1\160\1\314\26\30\21\0\1\27"+
    "\4\0\1\27\2\0\1\315\27\30\21\0\1\27\4\0"+
    "\1\27\2\0\1\160\4\30\1\316\22\30\3\0\2\25"+
    "\1\0\20\25\1\317\2\25\30\317\3\25\16\0\1\261"+
    "\4\0\1\261\2\0\30\261\1\0\1\320\17\0\1\262"+
    "\4\0\1\262\2\0\30\262\1\0\1\67\1\0\1\67"+
    "\2\0\1\67\1\0\1\67\1\70\1\67\1\0\7\67"+
    "\1\0\6\67\1\321\26\67\2\0\2\67\2\0\1\67"+
    "\1\0\1\67\1\70\1\67\1\0\7\67\1\0\30\67"+
    "\1\322\4\67\2\0\2\67\2\0\1\67\1\0\1\67"+
    "\1\70\1\67\1\0\7\67\1\0\21\67\1\323\13\67"+
    "\2\0\2\67\2\0\1\67\1\0\1\67\1\70\1\67"+
    "\1\0\7\67\1\0\6\67\1\324\26\67\2\0\1\67"+
    "\16\0\1\267\4\0\1\267\2\0\30\267\1\0\1\52"+
    "\1\0\1\52\2\0\1\52\1\0\1\52\1\77\1\52"+
    "\1\0\7\52\2\0\5\52\1\325\26\52\2\0\2\52"+
    "\2\0\1\52\1\0\1\52\1\77\1\52\1\0\7\52"+
    "\2\0\11\52\1\326\22\52\2\0\2\52\2\0\1\52"+
    "\1\0\1\52\1\77\1\52\1\0\7\52\2\0\20\52"+
    "\1\327\13\52\2\0\2\52\2\0\1\52\1\0\1\52"+
    "\1\77\1\52\1\0\7\52\2\0\32\52\1\330\1\52"+
    "\2\0\2\52\2\0\1\52\1\0\1\52\1\77\1\52"+
    "\1\0\7\52\2\0\13\52\1\331\20\52\2\0\1\52"+
    "\16\0\1\276\4\0\1\276\2\0\30\276\1\0\1\275"+
    "\24\0\1\332\2\0\30\332\3\0\1\300\1\25\1\0"+
    "\1\300\1\25\1\300\1\231\1\300\1\25\7\300\2\25"+
    "\34\300\2\25\1\300\2\25\1\0\20\25\1\333\2\25"+
    "\30\333\3\25\1\302\1\25\1\0\1\302\1\25\1\302"+
    "\1\25\1\302\1\25\7\302\1\25\35\302\2\25\1\302"+
    "\16\0\1\304\4\0\1\304\2\0\30\304\1\0\1\334"+
    "\17\0\1\335\42\0\1\132\2\0\1\132\1\0\1\132"+
    "\1\226\1\132\1\0\4\132\1\137\2\132\2\0\1\227"+
    "\33\132\2\0\1\132\1\52\2\0\1\52\1\0\1\52"+
    "\1\77\1\52\1\0\7\52\2\0\20\52\1\336\13\52"+
    "\2\0\2\52\2\0\1\52\1\0\1\52\1\77\1\52"+
    "\1\0\7\52\2\0\5\52\1\337\26\52\2\0\2\52"+
    "\2\0\1\52\1\0\1\52\1\77\1\52\1\0\7\52"+
    "\2\0\20\52\1\340\13\52\2\0\2\52\2\0\1\52"+
    "\1\0\1\52\1\77\1\52\1\0\7\52\2\0\5\52"+
    "\1\341\26\52\2\0\1\52\16\0\1\27\4\0\1\27"+
    "\2\0\1\342\27\30\21\0\1\27\4\0\1\27\2\0"+
    "\1\160\22\30\1\343\4\30\21\0\1\27\4\0\1\27"+
    "\2\0\1\160\1\30\1\251\12\30\1\344\12\30\21\0"+
    "\1\27\4\0\1\27\2\0\1\160\21\30\1\345\5\30"+
    "\3\0\2\25\1\0\13\25\1\317\4\25\1\317\2\25"+
    "\30\317\1\25\1\54\1\25\1\67\2\0\1\67\1\0"+
    "\1\67\1\70\1\67\1\0\7\67\1\0\31\67\1\346"+
    "\3\67\2\0\2\67\2\0\1\67\1\0\1\67\1\70"+
    "\1\67\1\0\7\67\1\0\23\67\1\347\11\67\2\0"+
    "\2\67\2\0\1\67\1\0\1\67\1\70\1\67\1\0"+
    "\7\67\1\0\31\67\1\350\3\67\2\0\2\67\2\0"+
    "\1\67\1\0\1\67\1\70\1\67\1\0\7\67\1\0"+
    "\30\67\1\351\4\67\2\0\1\67\1\52\2\0\1\52"+
    "\1\0\1\52\1\77\1\52\1\0\7\52\2\0\30\52"+
    "\1\352\3\52\2\0\2\52\2\0\1\52\1\0\1\52"+
    "\1\77\1\52\1\0\7\52\2\0\27\52\1\353\4\52"+
    "\2\0\2\52\2\0\1\52\1\0\1\52\1\77\1\52"+
    "\1\0\7\52\2\0\30\52\1\354\3\52\2\0\2\52"+
    "\2\0\1\52\1\0\1\52\1\77\1\52\1\0\7\52"+
    "\2\0\33\52\1\355\2\0\2\52\2\0\1\52\1\0"+
    "\1\52\1\77\1\52\1\0\7\52\2\0\11\52\1\356"+
    "\22\52\2\0\1\52\16\0\1\332\4\0\1\332\2\0"+
    "\30\332\1\0\1\233\1\0\2\25\1\0\13\25\1\333"+
    "\4\25\1\333\2\25\30\333\1\25\1\300\1\25\1\52"+
    "\2\0\1\52\1\0\1\52\1\77\1\52\1\0\7\52"+
    "\2\0\30\52\1\357\3\52\2\0\2\52\2\0\1\52"+
    "\1\0\1\52\1\77\1\52\1\0\7\52\2\0\30\52"+
    "\1\360\3\52\2\0\2\52\2\0\1\52\1\0\1\52"+
    "\1\77\1\52\1\0\7\52\2\0\30\52\1\361\3\52"+
    "\2\0\2\52\2\0\1\52\1\0\1\52\1\77\1\52"+
    "\1\0\7\52\2\0\27\52\1\362\4\52\2\0\1\52"+
    "\16\0\1\27\4\0\1\27\2\0\1\160\1\30\1\251"+
    "\11\30\1\363\13\30\21\0\1\27\4\0\1\27\2\0"+
    "\1\160\10\30\1\364\16\30\21\0\1\27\4\0\1\27"+
    "\2\0\1\160\1\365\26\30\3\0\1\67\2\0\1\67"+
    "\1\0\1\67\1\70\1\67\1\0\7\67\1\0\21\67"+
    "\1\366\13\67\2\0\2\67\2\0\1\67\1\0\1\67"+
    "\1\70\1\67\1\0\7\67\1\0\6\67\1\367\26\67"+
    "\2\0\2\67\2\0\1\67\1\0\1\67\1\70\1\67"+
    "\1\0\7\67\1\0\11\67\1\370\23\67\2\0\2\67"+
    "\2\0\1\67\1\0\1\67\1\70\1\67\1\0\7\67"+
    "\1\0\16\67\1\371\16\67\2\0\1\67\1\52\2\0"+
    "\1\52\1\0\1\52\1\77\1\52\1\0\7\52\2\0"+
    "\20\52\1\372\13\52\2\0\2\52\2\0\1\52\1\0"+
    "\1\52\1\77\1\52\1\0\7\52\2\0\11\52\1\373"+
    "\22\52\2\0\2\52\2\0\1\52\1\0\1\52\1\77"+
    "\1\52\1\0\7\52\2\0\10\52\1\374\23\52\2\0"+
    "\2\52\2\0\1\52\1\0\1\52\1\77\1\52\1\0"+
    "\7\52\2\0\26\52\1\375\5\52\2\0\2\52\2\0"+
    "\1\52\1\0\1\52\1\77\1\52\1\0\7\52\2\0"+
    "\10\52\1\376\23\52\2\0\2\52\2\0\1\52\1\0"+
    "\1\52\1\77\1\52\1\0\7\52\2\0\20\52\1\377"+
    "\13\52\2\0\2\52\2\0\1\52\1\0\1\52\1\77"+
    "\1\52\1\0\7\52\2\0\10\52\1\u0100\23\52\2\0"+
    "\2\52\2\0\1\52\1\0\1\52\1\77\1\52\1\0"+
    "\7\52\2\0\15\52\1\u0101\16\52\2\0\1\52\16\0"+
    "\1\27\4\0\1\27\2\0\1\160\23\30\1\u0102\3\30"+
    "\21\0\1\27\4\0\1\27\2\0\1\160\16\30\1\u0103"+
    "\10\30\21\0\1\27\4\0\1\27\2\0\1\160\17\30"+
    "\1\u0104\7\30\3\0\1\67\2\0\1\67\1\0\1\67"+
    "\1\70\1\67\1\0\7\67\1\0\30\67\1\u0105\4\67"+
    "\2\0\2\67\2\0\1\67\1\0\1\67\1\70\1\67"+
    "\1\0\7\67\1\0\22\67\1\u0106\12\67\2\0\2\67"+
    "\2\0\1\67\1\0\1\67\1\70\1\67\1\0\7\67"+
    "\1\0\12\67\1\u0107\22\67\2\0\2\67\2\0\1\67"+
    "\1\0\1\67\1\70\1\67\1\0\7\67\1\0\21\67"+
    "\1\u0108\13\67\2\0\1\67\1\52\2\0\1\52\1\0"+
    "\1\52\1\77\1\52\1\0\7\52\2\0\27\52\1\u0109"+
    "\4\52\2\0\2\52\2\0\1\52\1\0\1\52\1\77"+
    "\1\52\1\0\7\52\2\0\11\52\1\u010a\22\52\2\0"+
    "\2\52\2\0\1\52\1\0\1\52\1\77\1\52\1\0"+
    "\7\52\2\0\11\52\1\u010b\22\52\2\0\2\52\2\0"+
    "\1\52\1\0\1\52\1\77\1\52\1\0\7\52\2\0"+
    "\27\52\1\u010c\4\52\2\0\2\52\2\0\1\52\1\0"+
    "\1\52\1\77\1\52\1\0\7\52\2\0\11\52\1\u010d"+
    "\22\52\2\0\2\52\2\0\1\52\1\0\1\52\1\77"+
    "\1\52\1\0\7\52\2\0\20\52\1\u010e\13\52\2\0"+
    "\1\52\16\0\1\27\4\0\1\27\2\0\1\160\1\u010f"+
    "\26\30\21\0\1\27\4\0\1\27\2\0\1\160\15\30"+
    "\1\u0110\11\30\3\0\1\67\2\0\1\67\1\0\1\67"+
    "\1\70\1\67\1\0\7\67\1\0\12\67\1\u0111\22\67"+
    "\2\0\2\67\2\0\1\67\1\0\1\67\1\70\1\67"+
    "\1\0\7\67\1\0\12\67\1\u0112\22\67\2\0\1\67"+
    "\1\52\2\0\1\52\1\0\1\52\1\77\1\52\1\0"+
    "\7\52\2\0\11\52\1\u0113\22\52\2\0\1\52\16\0"+
    "\1\27\4\0\1\27\2\0\1\u0114\27\30\3\0\1\67"+
    "\2\0\1\67\1\0\1\67\1\70\1\67\1\0\7\67"+
    "\1\0\27\67\1\u0115\5\67\2\0\1\67\16\0\1\27"+
    "\4\0\1\27\2\0\1\160\1\30\1\u0116\25\30\21\0"+
    "\1\27\4\0\1\27\2\0\1\160\13\30\1\u0117\12\30"+
    "\1\313\21\0\1\27\4\0\1\27\2\0\1\160\16\30"+
    "\1\u0118\10\30\21\0\1\27\4\0\1\27\2\0\1\160"+
    "\2\30\1\u0119\24\30\21\0\1\27\4\0\1\27\2\0"+
    "\1\160\12\30\1\u011a\14\30\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[10731];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\22\0\1\11\13\1\1\11\3\1\1\11\2\1\1\11"+
    "\4\1\1\11\2\1\2\11\1\1\1\11\2\1\3\11"+
    "\6\1\2\11\5\1\2\11\2\1\1\11\2\1\3\11"+
    "\4\1\1\11\11\1\1\11\3\1\2\11\5\1\1\11"+
    "\1\1\1\11\5\1\1\0\7\1\1\0\3\1\2\0"+
    "\4\1\2\0\4\1\1\0\10\1\1\0\1\1\1\0"+
    "\1\1\1\0\3\1\1\11\5\1\1\0\1\1\1\0"+
    "\7\1\1\11\6\1\1\11\2\1\1\0\4\1\1\0"+
    "\5\1\1\11\1\1\1\0\3\1\1\11\1\1\1\0"+
    "\24\1\1\0\2\1\1\11\75\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[282];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  public NginxLexer() {
      this((java.io.Reader)null);
  }

  Deque<Integer> stack = new ArrayDeque<Integer>();

  // Track nested parentheses depth inside IF_PAREN_STATE
  int ifParenDepth = 0;

  // nginx quirk (issue #77): nginx's if-directive handler does NOT track parenthesis depth.
  // Instead, it tokenizes the condition normally (respecting quotes), then strips a trailing ')'
  // from the LAST token before '{' to use as the closing paren of if(...).
  //
  // Example: if ($arg_a ~ "x)"{  — nginx tokenizes "x)" as token 'x)', strips trailing ')' →
  // regex becomes 'x', and '{' opens the block. No explicit ')' needed after the string.
  //
  // Our lexer uses ifParenDepth tracking which is more correct, but to match nginx behavior
  // we allow '{' in IF_PAREN_STATE when a quoted string in the condition contained ')'.
  // See also: IF_STRING_STATE, IF_DQSTRING_STATE, and the LBRACE rule in IF_PAREN_STATE.
  boolean ifCloseParenInString = false;

  // Check if string ends with an unbalanced ')'.
  // nginx strips trailing ')' from the last token regardless of balance,
  // so "x)" has an unbalanced ')' (nginx strips it), but "(x)" is balanced (nginx strips it too,
  // breaking the regex). We only set the quirk flag when the string ends with ')' AND
  // closing parens outnumber opening ones — i.e. there's an "extra" ')' at the end.
  private boolean endsWithUnbalancedParen(String s) {
      if (!s.endsWith(")")) return false;
      int depth = 0;
      for (int i = 0; i < s.length(); i++) {
          char c = s.charAt(i);
          if (c == '(') depth++;
          else if (c == ')') depth--;
      }
      return depth < 0;
  }

  // Concatenation join handling: emit a synthetic CONCAT_JOIN token
  // between two adjacent atoms (VARIABLE/IDENTIFIER/VALUE/STRING) with no separators.
  boolean joinPending = false;           // true when we pushed back current token to emit CONCAT_JOIN
  boolean prevConcatEligible = false;    // true if the last emitted token completed a concat atom

  public final void yypush(int newState) {
      yybegin(newState);
      stack.push(newState);
  }

  public final int yycurrentState() {
      int state = stack.isEmpty() ? YYINITIAL : stack.peek();
      return state;
  }

  public final int yypop() {
      if (stack.isEmpty()) {
          yyinitial();
          return YYINITIAL;
      }

      int state = stack.pop();

      if (!stack.isEmpty()) {
          yybegin(stack.peek());
      } else {
          yyinitial();
      }

      return state;
  }

  public final void yyinitial() {
      stack.clear();
      yypush(YYINITIAL);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public NginxLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { yyinitial(); return BAD_CHARACTER;
            }
          // fall through
          case 72: break;
          case 2:
            { prevConcatEligible = false; joinPending = false; return WHITE_SPACE;
            }
          // fall through
          case 73: break;
          case 3:
            { prevConcatEligible = false; joinPending = false; return COMMENT;
            }
          // fall through
          case 74: break;
          case 4:
            { yypush(DIRECTIVE_STATE); return IDENTIFIER;
            }
          // fall through
          case 75: break;
          case 5:
            { prevConcatEligible = false; joinPending = false; return RBRACE;
            }
          // fall through
          case 76: break;
          case 6:
            { return STRING;
            }
          // fall through
          case 77: break;
          case 7:
            { yypop(); prevConcatEligible = true; return QUOTE;
            }
          // fall through
          case 78: break;
          case 8:
            { return DQSTRING;
            }
          // fall through
          case 79: break;
          case 9:
            { yypop(); prevConcatEligible = true; return DQUOTE;
            }
          // fall through
          case 80: break;
          case 10:
            { return VALUE;
            }
          // fall through
          case 81: break;
          case 11:
            { yypush(DQSTRING_STATE); return DQUOTE;
            }
          // fall through
          case 82: break;
          case 12:
            { yypush(STRING_STATE); return QUOTE;
            }
          // fall through
          case 83: break;
          case 13:
            { return SEMICOLON;
            }
          // fall through
          case 84: break;
          case 14:
            { return IDENTIFIER;
            }
          // fall through
          case 85: break;
          case 15:
            { yypush(LUA_STATE); return LBRACE;
            }
          // fall through
          case 86: break;
          case 16:
            { return LUA;
            }
          // fall through
          case 87: break;
          case 17:
            { yypush(LUA_STATE);
          return LUA;
            }
          // fall through
          case 88: break;
          case 18:
            { yypop();
          if (yycurrentState() == LUA_STATE) return LUA;
          yypop();
          return RBRACE;
            }
          // fall through
          case 89: break;
          case 19:
            { yypush(MAP_BLOCK_STATE); return LBRACE;
            }
          // fall through
          case 90: break;
          case 20:
            { yypop(); yypop(); return RBRACE;
            }
          // fall through
          case 91: break;
          case 21:
            { yypush(GEO_BLOCK_STATE); return LBRACE;
            }
          // fall through
          case 92: break;
          case 22:
            { // Enter condition parentheses; reset nested depth
          ifParenDepth = 0;
          ifCloseParenInString = false;
          yypush(IF_PAREN_STATE);
          return LPAREN;
            }
          // fall through
          case 93: break;
          case 23:
            { yypop(); joinPending = false; prevConcatEligible = false; return LBRACE;
            }
          // fall through
          case 94: break;
          case 24:
            { if (prevConcatEligible && !joinPending) { joinPending = true; yypushback(yylength()); return CONCAT_JOIN; }
          joinPending = false; prevConcatEligible = true; return VALUE;
            }
          // fall through
          case 95: break;
          case 25:
            { if (prevConcatEligible && !joinPending) { joinPending = true; yypushback(yylength()); return CONCAT_JOIN; }
          joinPending = false; prevConcatEligible = false; yypush(IF_DQSTRING_STATE); return DQUOTE;
            }
          // fall through
          case 96: break;
          case 26:
            { if (prevConcatEligible && !joinPending) { joinPending = true; yypushback(yylength()); return CONCAT_JOIN; }
          joinPending = false; prevConcatEligible = false; yypush(IF_STRING_STATE); return QUOTE;
            }
          // fall through
          case 97: break;
          case 27:
            { ifParenDepth++; return VALUE;
            }
          // fall through
          case 98: break;
          case 28:
            { if (ifParenDepth > 0) { ifParenDepth--; return VALUE; }
          if (ifCloseParenInString) {
              // nginx quirk: ) inside a quoted string already "closed" the if(),
              // so this explicit ) is extra — treat as syntax error.
              yypop(); // pop IF_PAREN_STATE -> IF_STATE
              yypop(); // pop IF_STATE -> YYINITIAL
              joinPending = false; prevConcatEligible = false;
              ifCloseParenInString = false;
              return BAD_CHARACTER;
          }
          yypop();
          return RPAREN;
            }
          // fall through
          case 99: break;
          case 29:
            { return EQUAL;
            }
          // fall through
          case 100: break;
          case 30:
            { if (prevConcatEligible && !joinPending) { joinPending = true; yypushback(yylength()); return CONCAT_JOIN; }
          joinPending = false; prevConcatEligible = true; return IDENTIFIER;
            }
          // fall through
          case 101: break;
          case 31:
            { if (ifCloseParenInString) {
              yypop(); // pop IF_PAREN_STATE -> IF_STATE
              yypop(); // pop IF_STATE -> YYINITIAL
              joinPending = false; prevConcatEligible = false;
              ifCloseParenInString = false;
              return LBRACE;
          }
          // No ) was in any string — { is genuinely invalid here
          yyinitial();
          return BAD_CHARACTER;
            }
          // fall through
          case 102: break;
          case 32:
            { return BINARY_OPERATOR;
            }
          // fall through
          case 103: break;
          case 33:
            { if (endsWithUnbalancedParen(yytext().toString())) { ifCloseParenInString = true; }
          return STRING;
            }
          // fall through
          case 104: break;
          case 34:
            { if (endsWithUnbalancedParen(yytext().toString())) { ifCloseParenInString = true; }
          return DQSTRING;
            }
          // fall through
          case 105: break;
          case 35:
            { if (prevConcatEligible && !joinPending) { joinPending = true; yypushback(yylength()); return CONCAT_JOIN; }
        // Check if the matched VALUE contains a $variable reference ($var, ${var}, $1)
        // that should be a separate VARIABLE token due to longest-match consuming too much.
        String text = yytext().toString();
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '$' && i + 1 < text.length()) {
                char next = text.charAt(i + 1);
                if (next == '{') {
                    // Braced variable ${VAR} — split VALUE before it
                    int closeBrace = text.indexOf('}', i + 2);
                    if (closeBrace >= 0) {
                        if (i > 0) {
                            yypushback(text.length() - i);
                            joinPending = false; prevConcatEligible = true; return VALUE;
                        } else {
                            yypushback(text.length() - closeBrace - 1);
                            joinPending = false; prevConcatEligible = true; return VARIABLE;
                        }
                    }
                    continue;
                }
                if ((next >= 'a' && next <= 'z') || (next >= 'A' && next <= 'Z') || next == '_') {
                    // Bare $variable found — split VALUE before it
                    if (i > 0) {
                        yypushback(text.length() - i);
                        joinPending = false; prevConcatEligible = true; return VALUE;
                    } else {
                        // VALUE starts with $variable — find end of variable name and push back the rest
                        int varEnd = i + 1;
                        while (varEnd < text.length()) {
                            char c = text.charAt(varEnd);
                            if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_' || (c >= '0' && c <= '9')) {
                                varEnd++;
                            } else {
                                break;
                            }
                        }
                        yypushback(text.length() - varEnd);
                        joinPending = false; prevConcatEligible = true; return VARIABLE;
                    }
                }
                if (next >= '0' && next <= '9') {
                    // Capture group reference $1, $2, etc. — split VALUE before it
                    if (i > 0) {
                        yypushback(text.length() - i);
                        joinPending = false; prevConcatEligible = true; return VALUE;
                    } else {
                        // VALUE starts with $N — find end of digits and push back the rest
                        int varEnd = i + 1;
                        while (varEnd < text.length()) {
                            char c = text.charAt(varEnd);
                            if (c >= '0' && c <= '9') {
                                varEnd++;
                            } else {
                                break;
                            }
                        }
                        yypushback(text.length() - varEnd);
                        joinPending = false; prevConcatEligible = true; return VARIABLE;
                    }
                }
            }
        }
        joinPending = false; prevConcatEligible = true; return VALUE;
            }
          // fall through
          case 106: break;
          case 36:
            { if (prevConcatEligible && !joinPending) { joinPending = true; yypushback(yylength()); return CONCAT_JOIN; }
        joinPending = false; prevConcatEligible = false; yypush(DQSTRING_STATE); return DQUOTE;
            }
          // fall through
          case 107: break;
          case 37:
            { if (prevConcatEligible && !joinPending) { joinPending = true; yypushback(yylength()); return CONCAT_JOIN; }
        joinPending = false; prevConcatEligible = false; yypush(STRING_STATE); return QUOTE;
            }
          // fall through
          case 108: break;
          case 38:
            { yypop(); joinPending = false; prevConcatEligible = false; return SEMICOLON;
            }
          // fall through
          case 109: break;
          case 39:
            { joinPending = false; prevConcatEligible = false; return EQUAL;
            }
          // fall through
          case 110: break;
          case 40:
            { if (prevConcatEligible && !joinPending) { joinPending = true; yypushback(yylength()); return CONCAT_JOIN; }
        joinPending = false; prevConcatEligible = true; return IDENTIFIER;
            }
          // fall through
          case 111: break;
          case 41:
            { joinPending = false; prevConcatEligible = false; return BINARY_OPERATOR;
            }
          // fall through
          case 112: break;
          case 42:
            { yypush(TYPES_BLOCK_STATE); return LBRACE;
            }
          // fall through
          case 113: break;
          case 43:
            { yypush(NUM_MAP_BLOCK_STATE); return LBRACE;
            }
          // fall through
          case 114: break;
          case 44:
            { yypush(DIRECTIVE_STATE); return VARIABLE;
            }
          // fall through
          case 115: break;
          case 45:
            { yypush(IF_STATE); return IF;
            }
          // fall through
          case 116: break;
          case 46:
            { return VARIABLE;
            }
          // fall through
          case 117: break;
          case 47:
            { if (prevConcatEligible && !joinPending) { joinPending = true; yypushback(yylength()); return CONCAT_JOIN; }
          joinPending = false; prevConcatEligible = true; return VARIABLE;
            }
          // fall through
          case 118: break;
          case 48:
            { return UNARY_OPERATOR;
            }
          // fall through
          case 119: break;
          case 49:
            { if (prevConcatEligible && !joinPending) { joinPending = true; yypushback(yylength()); return CONCAT_JOIN; }
        joinPending = false; prevConcatEligible = true; return VALUE;
            }
          // fall through
          case 120: break;
          case 50:
            { if (prevConcatEligible && !joinPending) { joinPending = true; yypushback(yylength()); return CONCAT_JOIN; }
        joinPending = false; prevConcatEligible = true; return VARIABLE;
            }
          // fall through
          case 121: break;
          case 51:
            { joinPending = false; prevConcatEligible = false; return CARET_TILDE;
            }
          // fall through
          case 122: break;
          case 52:
            { yypush(GEO_STATE); return GEO;
            }
          // fall through
          case 123: break;
          case 53:
            { yypush(MAP_STATE); return MAP;
            }
          // fall through
          case 124: break;
          case 54:
            { if (prevConcatEligible && !joinPending) {
            // Previous token was adjacent (no space) - this is a named parameter like "max=200"
            // Push back all but the '=' and return EQUAL token
            yypushback(yylength() - 1);
            joinPending = false;
            prevConcatEligible = false;
            return EQUAL;
        }
        // Space before = means this is a standalone status code like "=404"
        joinPending = false; prevConcatEligible = true; return VALUE;
            }
          // fall through
          case 125: break;
          case 55:
            { yypush(TYPES_STATE); return TYPES;
            }
          // fall through
          case 126: break;
          case 56:
            { return GEO_PROXY;
            }
          // fall through
          case 127: break;
          case 57:
            { return GEO_DELETE;
            }
          // fall through
          case 128: break;
          case 58:
            { return GEO_RANGES;
            }
          // fall through
          case 129: break;
          case 59:
            { yypush(NUM_MAP_STATE); return NUM_MAP;
            }
          // fall through
          case 130: break;
          case 60:
            { return MAP_DEFAULT;
            }
          // fall through
          case 131: break;
          case 61:
            { return MAP_INCLUDE;
            }
          // fall through
          case 132: break;
          case 62:
            { return GEO_DEFAULT;
            }
          // fall through
          case 133: break;
          case 63:
            { return GEO_INCLUDE;
            }
          // fall through
          case 134: break;
          case 64:
            { return TYPES_INCLUDE;
            }
          // fall through
          case 135: break;
          case 65:
            { return NUM_MAP_DEFAULT;
            }
          // fall through
          case 136: break;
          case 66:
            { return NUM_MAP_INCLUDE;
            }
          // fall through
          case 137: break;
          case 67:
            { yypush(DIRECTIVE_STATE); return LOCATION;
            }
          // fall through
          case 138: break;
          case 68:
            { return MAP_VOLATILE;
            }
          // fall through
          case 139: break;
          case 69:
            { return NUM_MAP_VOLATILE;
            }
          // fall through
          case 140: break;
          case 70:
            { return MAP_HOSTNAMES;
            }
          // fall through
          case 141: break;
          case 71:
            { yypush(LUA_BLOCK_STATE); return LUA_BLOCK_DIRECTIVE;
            }
          // fall through
          case 142: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
