package dev.meanmail.codeInsight.completion.directives

// https://nginx.org/en/docs/stream/ngx_stream_core_module.html

val streamListen = Directive("listen")
val streamPrereadBufferSize = Directive(
    "preread_buffer_size",
    defaultValue = "16k"
)
val streamPrereadTimeout = Directive(
    "preread_timeout",
    defaultValue = "30s"
)
val streamProxyProtocolTimeout = Directive(
    "proxy_protocol_timeout",
    defaultValue = "30s"
)
val streamResolver = Directive("resolver")
val streamResolverTimeout = Directive(
    "resolver_timeout",
    defaultValue = "30s"
)
val streamTcpNodelay = ToggleDirective("tcp_nodelay", true)
val streamServer = Directive(
    "server",
    children = setOf(
        streamListen,
        streamPrereadBufferSize,
        streamPrereadTimeout,
        streamProxyProtocolTimeout,
        streamResolver,
        streamResolverTimeout,
        streamTcpNodelay,
        streamAllow,
        streamDeny,
        streamJsAccess,
        streamJsFilter,
        streamJsPreread,
        streamJsFetchCiphers,
        streamJsFetchProtocols,
        streamJsFetchTrustedCertificate,
        streamJsFetchVerifyDepth,
        streamLimitConn,
        streamLimitConnDryRun,
        streamLimitConnLogLevel,
        streamAccessLog,
        streamOpenLogFileCache,
        streamProxyBind,
        streamProxyBufferSize,
        streamProxyConnectTimeout,
        streamProxyDownloadRate,
        streamProxyHalfClose,
        streamProxyNextUpstream,
        streamProxyNextUpstreamTimeout,
        streamProxyNextUpstreamTries,
        streamProxyPass,
        streamProxyProtocol,
        streamProxyRequests,
        streamProxyResponses,
        streamProxySessionDrop,
        streamProxySocketKeepalive,
        streamProxySsl,
        streamProxySslCertificate,
        streamProxySslCertificateKey,
        streamProxySslCiphers,
        streamProxySslConfCommand,
        streamProxySslCrl,
        streamProxySslName,
        streamProxySslPasswordFile,
        streamProxySslProtocols,
        streamProxySslServerName,
        streamProxySslSessionReuse,
        streamProxySslTrustedCertificate,
        streamProxySslVerify,
        streamProxySslVerifyDepth,
        streamProxyTimeout,
        streamProxyUploadRate,
        streamSetRealIpFrom,
        streamReturn,
        streamSet,
        streamSslAlpn,
        streamSslCertificate,
        streamSslCertificateKey,
        streamSslCiphers,
        streamSslClientCertificate,
        streamSslConfCommand,
        streamSslCrl,
        streamSslDhparam,
        streamSslEcdhCurve,
        streamSslHandshakeTimeout,
        streamSslPasswordFile,
        streamSslPreferServerCiphers,
        streamSslProtocols,
        streamSslSessionCache,
        streamSslSessionTicketKey,
        streamSslSessionTickets,
        streamSslSessionTimeout,
        streamSslTrustedCertificate,
        streamSslVerifyClient,
        streamSslVerifyDepth,
        streamSslPreread,
        streamUpstreamHealthCheck,
        streamUpstreamHealthCheckTimeout,
        streamZoneSync,
        streamZoneSyncBuffers,
        streamZoneSyncConnectRetryInterval,
        streamZoneSyncConnectTimeout,
        streamZoneSyncInterval,
        streamZoneSyncRecvBufferSize,
        streamZoneSyncServer,
        streamZoneSyncSsl,
        streamZoneSyncSslCertificate,
        streamZoneSyncSslCertificateKey,
        streamZoneSyncSslCiphers,
        streamZoneSyncSslConfCommand,
        streamZoneSyncSslCrl,
        streamZoneSyncSslName,
        streamZoneSyncSslPasswordFile,
        streamZoneSyncSslProtocols,
        streamZoneSyncSslServerName,
        streamZoneSyncSslTrustedCertificate,
        streamZoneSyncSslVerify,
        streamZoneSyncSslVerifyDepth,
        streamZoneSyncTimeout,
    )
)

val streamVariablesHashBucketSize = Directive(
    "variables_hash_bucket_size",
    defaultValue = "64"
)
val streamVariablesHashMaxSize = Directive(
    "variables_hash_max_size",
    defaultValue = "1024"
)

val stream = Directive(
    "stream",
    children = setOf(
        errorLog,
        streamServer,
        streamPrereadBufferSize,
        streamPrereadTimeout,
        streamProxyProtocolTimeout,
        streamResolver,
        streamResolverTimeout,
        streamTcpNodelay,
        streamVariablesHashBucketSize,
        streamVariablesHashMaxSize,
        streamAllow,
        streamDeny,
        streamGeo,
        streamGeoipCountry,
        streamGeoipCity,
        streamGeoipOrg,
        streamJsAccess,
        streamJsFilter,
        streamJsImport,
        streamJsInclude,
        streamJsPreread,
        streamJsPath,
        streamJsSet,
        streamJsVar,
        streamKeyval,
        streamKeyvalZone,
        streamLimitConn,
        streamLimitConnDryRun,
        streamLimitConnLogLevel,
        streamLimitConnZone,
        streamAccessLog,
        streamLogFormat,
        streamOpenLogFileCache,
        streamMap,
        streamMapHashBucketSize,
        streamMapHashMaxSize,
        streamProxyBind,
        streamProxyBufferSize,
        streamProxyConnectTimeout,
        streamProxyDownloadRate,
        streamProxyHalfClose,
        streamProxyNextUpstream,
        streamProxyNextUpstreamTimeout,
        streamProxyNextUpstreamTries,
        streamProxyProtocol,
        streamProxyRequests,
        streamProxyResponses,
        streamProxySessionDrop,
        streamProxySocketKeepalive,
        streamProxySsl,
        streamProxySslCertificate,
        streamProxySslCertificateKey,
        streamProxySslCiphers,
        streamProxySslConfCommand,
        streamProxySslCrl,
        streamProxySslName,
        streamProxySslPasswordFile,
        streamProxySslProtocols,
        streamProxySslServerName,
        streamProxySslSessionReuse,
        streamProxySslTrustedCertificate,
        streamProxySslVerify,
        streamProxySslVerifyDepth,
        streamProxyTimeout,
        streamProxyUploadRate,
        streamSetRealIpFrom,
        streamSplitClients,
        streamSslAlpn,
        streamSslCertificate,
        streamSslCertificateKey,
        streamSslCiphers,
        streamSslClientCertificate,
        streamSslConfCommand,
        streamSslCrl,
        streamSslDhparam,
        streamSslEcdhCurve,
        streamSslHandshakeTimeout,
        streamSslPasswordFile,
        streamSslPreferServerCiphers,
        streamSslProtocols,
        streamSslSessionCache,
        streamSslSessionTicketKey,
        streamSslSessionTickets,
        streamSslSessionTimeout,
        streamSslTrustedCertificate,
        streamSslVerifyClient,
        streamSslVerifyDepth,
        streamSslPreread,
        streamUpstream,
        streamUpstreamHealthCheckTimeout,
        streamUpstreamMatch,
        streamZoneSyncBuffers,
        streamZoneSyncConnectRetryInterval,
        streamZoneSyncConnectTimeout,
        streamZoneSyncInterval,
        streamZoneSyncRecvBufferSize,
        streamZoneSyncSsl,
        streamZoneSyncSslCertificate,
        streamZoneSyncSslCertificateKey,
        streamZoneSyncSslCiphers,
        streamZoneSyncSslConfCommand,
        streamZoneSyncSslCrl,
        streamZoneSyncSslName,
        streamZoneSyncSslPasswordFile,
        streamZoneSyncSslProtocols,
        streamZoneSyncSslServerName,
        streamZoneSyncSslTrustedCertificate,
        streamZoneSyncSslVerify,
        streamZoneSyncSslVerifyDepth,
        streamZoneSyncTimeout,
    )
)

val ngx_stream_core_module = Module(
    "ngx_stream_core_module",
    enabled = false,
    directives = setOf(
        stream,
        streamListen,
        streamPrereadBufferSize,
        streamPrereadTimeout,
        streamProxyProtocolTimeout,
        streamResolver,
        streamResolverTimeout,
        streamServer,
        streamTcpNodelay,
        streamVariablesHashBucketSize,
        streamVariablesHashMaxSize,
    )
)
